export const BLOG_SCHEMA = {
  TABLE: 'tbl_blog',
  FIELDS: {
    ID: 'id',
    LANGUAGE_ID: 'language_id',
    BLOG_CATEGORY_ID: 'blog_category_id',
    BLOG_AUTHOR_ID: 'blog_author_id',
    IMAGE: 'image',
    TITLE: 'title',
    SUB_TITLE: 'sub_title',
    DATE_CREATED: 'date_created',
    LAST_UPDATED: 'last_updated',
    VIEW: 'view',
    TABLE_OF_CONTENTS: 'table_of_contents',
    CONTENT: 'content',
    ROW_ORDER: 'row_order',
    SLUG: 'slug',
    SEO_BLOCK: 'seo_block',
    META_TITLE: 'meta_title',
    META_DESCRIPTION: 'meta_description',
    META_KEYWORD: 'meta_keyword',
    SCHEMA_MARKUP: 'schema_markup',
    DESCRIPTION: 'description',
    ARTICLE_TAGS: 'article_tags',
    QUIZ_ID: 'quiz_id',
  },
} as const;
