export const USERS_BADGES_SCHEMA = {
  TABLE: 'tbl_users_badges',
  FIELDS: {
    ID: 'id',
    USER_ID: 'user_id',
    DASHING_DEBUT: 'dashing_debut',
    DASHING_DEBUT_COUNTER: 'dashing_debut_counter',
    COMBAT_WINNER: 'combat_winner',
    COMBAT_WINNER_COUNTER: 'combat_winner_counter',
    CLASH_WINNER: 'clash_winner',
    CLASH_WINNER_COUNTER: 'clash_winner_counter',
    MOST_WANTED_WINNER: 'most_wanted_winner',
    MOST_WANTED_WINNER_COUNTER: 'most_wanted_winner_counter',
    ULTIMATE_PLAYER: 'ultimate_player',
    QUIZ_WARRIOR: 'quiz_warrior',
    QUIZ_WARRIOR_COUNTER: 'quiz_warrior_counter',
    SUPER_SONIC: 'super_sonic',
    FLASHBACK: 'flashback',
    BRAINIAC: 'brainiac',
    BIG_THING: 'big_thing',
    ELITE: 'elite',
    THIRSTY: 'thirsty',
    THIRSTY_DATE: 'thirsty_date',
    THIRSTY_COUNTER: 'thirsty_counter',
    POWER_ELITE: 'power_elite',
    POWER_ELITE_COUNTER: 'power_elite_counter',
    SHARING_CARING: 'sharing_caring',
    STREAK: 'streak',
    STREAK_DATE: 'streak_date',
    STREAK_COUNTER: 'streak_counter',
  },
};
