export const WEB_SEO_SCHEMA = {
  TABLE: 'tbl_web_seo',
  FIELDS: {
    ID: 'id',
    LANGUAGE_ID: 'language_id',
    QUIZZ_MODE: 'quizz_mode',
    TYPE: 'type',
    QUIZZ_BY_LANGUAGE_LAN_ID: 'quizz_by_language_lan_id',
    MAINCAT_ID: 'maincat_id',
    SUBCATEGORY_ID: 'subcategory_id',
    SUBCATEGORY_LEVEL_ID: 'subcategory_level_id',
    QUIZZ_ID: 'quizz_id',
    TITLE: 'title',
    SUB_HEADING: 'sub_heading',
    SLUG: 'slug',
    SEO_BLOCK: 'seo_block',
    META_TITLE: 'meta_title',
    META_DESCRIPTION: 'meta_description',
    META_KEYWORD: 'meta_keyword',
    SCHEMA_MARKUP: 'schema_markup',
    SPONSOR_LINK: 'sponsor_link',
    SPONSOR_NAME: 'sponsor_name',
    DESCRIPTION: 'description',
    IS_EDIT_SLUG: 'is_edit_slug',
    SUB_TITLE: 'sub_title',
    HEADING: 'heading',
    ENABLE_FAQ: 'enable_faq',
  },
} as const;
